package freewill.nextgen.project;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProjectFormDesign extends CssLayout {
    protected TextField Name;
    protected TextArea Description;
    protected PopupDateField Deliverydate;
    protected TextField Answers;
    protected CheckBox Active;
    protected TextField Company;
    protected ComboBox Language;
    protected ComboBox Status;
    protected TextField Answer;
    protected ListSelect List;
    protected HorizontalLayout Answers1Layout;
    protected VerticalLayout Answers2Layout;
    protected Button AddResp;
    protected Button DelResp;
    
    protected Image image;
    protected Button Add;
    protected Button Del;
    protected HorizontalLayout imageLayout;
    protected VerticalLayout imageLayout2;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public ProjectFormDesign() {
        Design.read(this);
    }
}