package freewill.nextgen.competicion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CompeticionFormDesign extends CssLayout {
	protected TextField nombre;
    protected TextField organizador;
    protected TextField localidad;
	protected ComboBox circuito;
    protected ComboBox tipo;
    protected DateField fechaInicio;
    protected DateField fechaFin;
    protected DateField fechaFinInscripcion;
    protected CheckBox active;
    protected CheckBox speed;
    protected CheckBox salto;
    protected CheckBox derrapes;
    protected CheckBox jam;
    protected CheckBox classic;
    protected CheckBox battle;
    protected Button closeCompeticion;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public CompeticionFormDesign() {
        Design.read(this);
    }
}