package freewill.nextgen.competicion.salto;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SaltoTrialFormDesign extends CssLayout {
	protected ComboBox salto1;
	protected ComboBox salto2;
	protected ComboBox salto3;
	protected TextField dorsal;
	protected TextField nombre;
	protected TextField apellidos;
	protected TextField altura;
	protected CheckBox ganaDesempate;
	
    protected Button save;
    protected Button cancel;

    public SaltoTrialFormDesign() {
        Design.read(this);
    }
}