package freewill.nextgen.competicion.jam;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TabSheet.Tab;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class JamShowFormDesign extends FormLayout /*CssLayout*/ {
	protected TextField tecnicaJuez1;				
	protected TextField artisticaJuez1;
	protected TextField sincronizacionJuez1;
	protected TextField tecnicaJuez2;
	protected TextField artisticaJuez2;
	protected TextField sincronizacionJuez2;
	protected TextField tecnicaJuez3;
	protected TextField artisticaJuez3;
	protected TextField sincronizacionJuez3;
	protected TextField penalizaciones;
	
    protected Button save;
    
    protected TabSheet tabSheet;
    protected Tab tabTodo;
    protected Tab tabJuez1;
    protected Tab tabJuez2;
    protected Tab tabJuez3;
    protected TextField tecnicaJuez1b;
	protected TextField artisticaJuez1b;
	protected TextField sincronizacionJuez1b;
	protected TextField tecnicaJuez2b;				
	protected TextField artisticaJuez2b;
	protected TextField sincronizacionJuez2b;
	protected TextField tecnicaJuez3b;				
	protected TextField artisticaJuez3b;
	protected TextField sincronizacionJuez3b;
	protected Button save1;
	protected Button save2;
	protected Button save3;
	protected Button expand;

    public JamShowFormDesign() {
        Design.read(this);
    }
}