package freewill.nextgen.categoria;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CategoriaFormDesign extends CssLayout {
	protected TextField nombre;
	protected ComboBox modalidad;
    protected TextField edadMinima;
    protected TextField edadMaxima;
    protected ComboBox genero;
    protected CheckBox active;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public CategoriaFormDesign() {
        Design.read(this);
    }
}