package freewill.nextgen.competicion.speed;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SpeedTimeTrialFormDesign1 extends FormLayout /*CssLayout*/ {
	protected TextField tiempo1A;				
	protected TextField tiempo1B;		
	protected ComboBox  conos1;			
	protected TextField tiempoAjustado1;	
    
    protected Button save;

    public SpeedTimeTrialFormDesign1() {
        Design.read(this);
    }
}