package freewill.nextgen.resultados;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ParticipanteFormDesign extends CssLayout {
	protected Button patinBtn;
	protected TextField patinador;
	protected TextField nombre;
    protected TextField apellidos;
    protected Button parejaBtn;
    protected TextField parejaJam;
	protected TextField patinadorPareja;
	protected TextField nombrePareja;
    protected TextField apellidosPareja;
    protected TextField clasificacion;
    protected TextField mejorMarca;
    protected TextField puntuacion;
    protected ComboBox club;
    protected TextField dorsal;
    protected TextField dorsalPareja;
    protected ComboBox competicion;
    protected ComboBox categoria;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public ParticipanteFormDesign() {
        Design.read(this);
    }
}