package freewill.nextgen.user;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserFormDesign extends CssLayout {
    protected TextField Name;
    protected TextField Loginname;
    protected TextField Email;
    protected PasswordField Password;
    protected ComboBox Language;
    protected ComboBox Role;
    protected CheckBox Active;
    protected TextField Company;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public UserFormDesign() {
        Design.read(this);
    }
}