package freewill.nextgen.mail;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MailServerFormDesign extends CssLayout {
    protected TextField Label;
    protected TextField Description;
    protected TextField Hostname;
    protected TextField Port;
    protected TextField Username;
    protected PasswordField Password;
    protected CheckBox Active;
    
    protected HorizontalLayout AvailableLayout;
    protected HorizontalLayout AssignedLayout;
    protected Button add;
    protected Button del;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public MailServerFormDesign() {
        Design.read(this);
    }
}