package freewill.nextgen.serverMonitor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ServerFormDesign extends CssLayout {
	protected TextField name;
	protected TextField timestamp;
	protected Label state;
	protected TextField site;
	protected TextField osname;
	
	protected VerticalLayout statebox;
	protected TabSheet tabsheet;
	
	protected HorizontalLayout ramcpu;
	protected HorizontalLayout disk;
	
	protected Label space;
    protected Button start;
    protected Button stop;
    protected Button close;

    public ServerFormDesign() {
        Design.read(this);
    }
}