package freewill.nextgen.competicion.classic;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ClassicShowFormDesign extends FormLayout /*CssLayout*/ {
	protected TextField tecnicaJuez1;				
	protected TextField artisticaJuez1;	
	protected TextField tecnicaJuez2;				
	protected TextField artisticaJuez2;	
	protected TextField tecnicaJuez3;				
	protected TextField artisticaJuez3;	
	protected TextField penalizaciones;
	
    protected Button save;

    public ClassicShowFormDesign() {
        Design.read(this);
    }
}