package freewill.nextgen.parejajam;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ParejaJamFormDesign extends CssLayout {
	protected Button patin1Btn;
	protected TextField patinador1;
	protected TextField nombre1;
    protected TextField apellidos1;
    protected Button patin2Btn;
	protected TextField patinador2;
	protected TextField nombre2;
    protected TextField apellidos2;
    protected ComboBox club;
    protected ComboBox categoria;
    
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public ParejaJamFormDesign() {
        Design.read(this);
    }
}