package freewill.nextgen.competicion.derrapes;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DerrapesRondaFormDesign extends CssLayout {
	protected TextField patina1;
	protected TextField patina2;
	protected TextField patina3;
	protected TextField patina4;
	protected ComboBox  ganador1;
	protected ComboBox  ganador2;
	protected ComboBox  ganador3;
	protected ComboBox  ganador4;
    
    protected Button save;
    protected Button cancel;

    public DerrapesRondaFormDesign() {
        Design.read(this);
    }
}